### ISSUE TITLE
archetype list 

### ISSUE THREAD

**Issue by donvitin** [Pi4J/pi4j-maven-archetype#3]
It request a archetype but I dont see the list.  Enter key just returns

**Comment by FDelporte** [comment]
@donvitin can you please provide full info? executed command and output?

**Comment by donvitin** [comment]
I attached a pic of command and output.   I tried the enter key but no
list.  Window 10 pro environment.   Thanks for your help.

**Comment by FDelporte** [comment]
@donvitin you will need to add the info directly in Github... no attachment added at this moment...

**Comment by donvitin** [comment]
C:\Users\vitit\.ssh>mvn archetype:generate -DarchetypeCatalog=local
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] >>> maven-archetype-plugin:3.2.0:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO]
[INFO] <<< maven-archetype-plugin:3.2.0:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO]
[INFO]
[INFO] --- maven-archetype-plugin:3.2.0:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Interactive mode
[INFO] No archetype defined. Using maven-archetype-quickstart (org.apache.maven.archetypes:maven-archetype-quickstart:1.0)
Choose archetype:
   Your filter doesn't match any archetype (hint: enter to return to initial list)
Choose a number or apply filter (format: [groupId:]artifactId, case sensitive contains): :
Choose archetype:
   Your filter doesn't match any archetype (hint: enter to return to initial list)
Choose a number or apply filter (format: [groupId:]artifactId, case sensitive contains): :

**Comment by FDelporte** [comment]
@donvitin did you follow the install step as described on https://pi4j.com/getting-started/developing-on-a-remote-pc/#configure-the-rpi-for-headless-mode?

@lburaggi can you assist here?

**Comment by donvitin** [comment]
Yes, I did. And return does not pop the list. I typed the archetype but it
does not  recognize.  I'll check tonight the the install steps will get
back to you. Thx for your support.

**Comment by donvitin** [comment]
Resolved:  forgot to mvn install the  local archetype.  Worked like a charm

**Comment by FDelporte** [comment]
Thanks for the update and happy this issue resolved itself ;-)

**Comment by donvitin** [comment]
Where can I find the constant defining gpio
