### ISSUE TITLE
Remote build fails

### ISSUE THREAD

**Issue by bigalnz** [Pi4J/pi4j-maven-archetype#6]
When running the mvn antrun:run@exec command to run the code remotely on a Pi Zero W I get the following error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:3.0.0:run (exec) on project pitest2: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] C:\Users\AlGrant\IdeaProjects\pitest2\antrun\build.xml:166: The following error occurred while executing this line:
[ERROR] C:\Users\AlGrant\IdeaProjects\pitest2\antrun\build.xml:123: Remote command failed with exit status 1
[ERROR] around Ant part ...<ant antfile="antrun/build.xml" target="run-remote" />... @ 9:59 in C:\Users\AlGrant\IdeaProjects\pitest2\target\antrun\build-main.xml
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Java version 11 on Pi.

**Comment by FDelporte** [comment]
@lburaggi you have an idea what could be going wrong here?

**Comment by bigalnz** [comment]
I had to install java /usr/lib/jvm/zulu11.41.75-ca-jdk11.0.8-linux_aarch32hf/bin/java for a Pi Zero W.

This then meant that the commands that involved /usr/lib/jvm/java-default would fail since java-default doesnt exist.

To fix this I changed in raspberry.properties the following line

target.remote.jre=/usr/lib/jvm/default-java

from the above to this (below)

target.remote.jre=/usr/lib/jvm/zulu11.41.75-ca-jdk11.0.8-linux_aarch32hf
